### ISSUE TITLE
Wireframe Design

### ISSUE THREAD

**Issue by AdishRao** [RoadTripppin/wazzup-client#1]

**Comment by AdishRao** [comment]
#4 Rough design for register page
![Register](https://user-images.githubusercontent.com/31245878/151495863-5ca914fc-cc99-498e-8560-2dfb4b38dce8.png)
@RoadTripppin/all

**Comment by AdishRao** [comment]
#3 Rough Design for Login Page
![Login](https://user-images.githubusercontent.com/31245878/151495971-0e35443f-859e-441d-87ed-c98286cc81fc.png)
@RoadTripppin/all

**Comment by AdishRao** [comment]
#5 Entire app rough design, containing individual components within (All differently covered)
![Main App](https://user-images.githubusercontent.com/31245878/151496656-42e9fefa-6ab0-42fa-bf87-b3f111d9faaa.png)
@RoadTripppin/all

**Comment by AdishRao** [comment]
#7 Rough design for update profile component
![Update Profile](https://user-images.githubusercontent.com/31245878/151499468-c033a3b6-ba75-463a-9845-a534b1e71f61.png)
@RoadTripppin/all

**Comment by AdishRao** [comment]
Reviewed and Approved by:

- [ ] @adiSuper94 
- [ ] @ashwin2303 
- [ ] @shashankbhat10 

Once reviewed, will close the issue.

**Comment by ashwin2303** [comment]
@AdishRao Reviewed and looks good!

**Comment by AdishRao** [comment]
Reviewed and accepted by all.
